[package]

name = "Rust_Playground"
version = "0.0.1"
authors = [ "Clara Benedicta Maria Mueller <clara.mueller@vilera.de>" ]


[[bin]]
name = "main"
path = "/media/win_e/Clara_Daten/etc/Programmierung/Rust/src/main.rs"


[dependencies]

rand="0.3.0"
