[package]

name = "hello_world"
version = "0.0.1"
authors = [ "Clara Benedicta Maria Mueller <clara.mueller@vilera.de>" ]

[[bin]]
name = "test"
path = "/media/win_e/Clara_Daten/etc/Programmierung/Rust/src/test.rs"
