[package]

name = "Rust_Playground"
version = "0.0.1"
authors = [ "Ananke" ]


[[bin]]
name = "stuff"
path = "passwordgenerator.rs"


[dependencies]
regex = "1"
rand = "0.3.15"
getopts = "0.2"
text_io = "0.1.7"
num-traits = "0.2"
lazy_static = "1.0"
